# Generated by Django 3.0.4 on 2020-03-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_quarantinecenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuarantineCenter',
        ),
    ]
