# Generated by Django 3.0.4 on 2020-03-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarantine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinecenter',
            name='capacity',
            field=models.IntegerField(default=1, help_text='Total number of ICUs in the quarantine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarantinecenter',
            name='occupied_units',
            field=models.IntegerField(default=100, help_text='Number of currently occupied ICUs'),
            preserve_default=False,
        ),
    ]
